### ISSUE TITLE
How to fix this : io.socket.SocketIOException: 1+0

### ISSUE THREAD

**Issue by sm-tester** [Gottox/socket.io-java-client#113]
12-11 14:24:06.434: I/io.socket(19947): > 2::
12-11 14:24:06.435: I/io.socket(19947): < 7:::1+0
12-11 14:24:06.436: I/SocketClient(19947): an Error occured, isConnected:true 
12-11 14:24:06.436: W/System.err(19947): io.socket.SocketIOException: 1+0
12-11 14:24:06.436: W/System.err(19947):    at io.socket.IOConnection.transportMessage(IOConnection.java:739)
12-11 14:24:06.436: W/System.err(19947):    at io.socket.WebsocketTransport.onMessage(WebsocketTransport.java:82)
12-11 14:24:06.436: W/System.err(19947):    at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:312)
12-11 14:24:06.436: W/System.err(19947):    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:368)
12-11 14:24:06.436: W/System.err(19947):    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:157)
12-11 14:24:06.436: W/System.err(19947):    at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:230)
12-11 14:24:06.437: W/System.err(19947):    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
12-11 14:24:06.437: W/System.err(19947):    at java.lang.Thread.run(Thread.java:818)

**Comment by vecharm** [comment]
Have you solved this problem, please?

**Comment by sm-tester** [comment]
@VipMinF no, did not solve. I'm using another library now. 
`https://github.com/socketio/socket.io-client-java`
