### ISSUE TITLE
Socket instantiation problem (Even i added socketio.jar  )

### ISSUE THREAD

**Issue by manjuojal** [Gottox/socket.io-java-client#123]
07-21 22:58:26.811: E/AndroidRuntime(3250): FATAL EXCEPTION: main
07-21 22:58:26.811: E/AndroidRuntime(3250): Process: com.example.chats, PID: 3250
07-21 22:58:26.811: E/AndroidRuntime(3250): java.lang.NoClassDefFoundError: Failed resolution of: Lio/socket/SocketIO;
07-21 22:58:26.811: E/AndroidRuntime(3250):     at com.example.chats.MainActivity.onCreate(MainActivity.java:26)
07-21 22:58:26.811: E/AndroidRuntime(3250):     at android.app.Activity.performCreate(Activity.java:5990)
07-21 22:58:26.811: E/AndroidRuntime(3250):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
07-21 22:58:26.811: E/AndroidRuntime(3250):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
07-21 22:58:26.811: E/AndroidRuntime(3250):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
07-21 22:58:26.811: E/AndroidRuntime(3250):     at android.app.ActivityThread.access$800(ActivityThread.java:151)
07-21 22:58:26.811: E/AndroidRuntime(3250):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
07-21 22:58:26.811: E/AndroidRuntime(3250):     at android.os.Handler.dispatchMessage(Handler.java:102)
07-21 22:58:26.811: E/AndroidRuntime(3250):     at android.os.Looper.loop(Looper.java:135)
07-21 22:58:26.811: E/AndroidRuntime(3250):     at android.app.ActivityThread.main(ActivityThread.java:5254)
07-21 22:58:26.811: E/AndroidRuntime(3250):     at java.lang.reflect.Method.invoke(Native Method)
07-21 22:58:26.811: E/AndroidRuntime(3250):     at java.lang.reflect.Method.invoke(Method.java:372)
07-21 22:58:26.811: E/AndroidRuntime(3250):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
07-21 22:58:26.811: E/AndroidRuntime(3250):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
07-21 22:58:26.811: E/AndroidRuntime(3250): Caused by: java.lang.ClassNotFoundException: Didn't find class "io.socket.SocketIO" on path: DexPathList[[zip file "/data/app/com.example.chats-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
07-21 22:58:26.811: E/AndroidRuntime(3250):     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
07-21 22:58:26.811: E/AndroidRuntime(3250):     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
07-21 22:58:26.811: E/AndroidRuntime(3250):     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
07-21 22:58:26.811: E/AndroidRuntime(3250):     ... 14 more
07-21 22:58:26.811: E/AndroidRuntime(3250):     Suppressed: java.lang.ClassNotFoundException: io.socket.SocketIO
07-21 22:58:26.811: E/AndroidRuntime(3250):         at java.lang.Class.classForName(Native Method)
07-21 22:58:26.811: E/AndroidRuntime(3250):         at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
07-21 22:58:26.811: E/AndroidRuntime(3250):         at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
07-21 22:58:26.811: E/AndroidRuntime(3250):         at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
07-21 22:58:26.811: E/AndroidRuntime(3250):         ... 15 more
07-21 22:58:26.811: E/AndroidRuntime(3250):     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by bback99** [comment]
same with me, how to solve this problem?

**Comment by bback99** [comment]
put full path of socketio.jar file

compile files('/Users/shoong/Documents/workspace/GDX/TileMapAndCharactor/core/src/lib/socketio.jar')

after it is working
