### ISSUE TITLE
Deadlock involving IOConnection instance and outputBuffer

### ISSUE THREAD

**Issue by EugenDueck** [Gottox/socket.io-java-client#16]
I'm running into deadlocks every now and then. Taking a thread dump revealed the objects involved. A socket.io-java-client thread called "ConnectThread" calls IOConnection.connectTransport, which locks, in this order
1. this (as connectTransport() is synchronized)
2. outputBuffer (explicitly in IOConnection.transportConnected()

Now my own thread calls SocketIO.emit, which locks, in this order
1. outputBuffer (explicitly in IOConnection.sendPlain())
2. this (by calling getState() which is synchronized)

Still not having had the time to go read the code, the quick fix for me was to make IOConnection.sendPlain(String) synchronized, which reverses the order that sendPlain() takes those 2 locks, thus averting the deadlock.

It works great for me so far (I'm creating 5000 client instances in a single JVM in a matter of seconds now), but there might be better ways to fix it for those who know the code. In any event, here are the relevant bits from the thread dump (line numbers seem to be off by 1, and maybe by more due to my local changes, so it's probably easier to just use the method names).
# Found one Java-level deadlock:

"Thread-5789":
  waiting to lock monitor 0x00002aab9be10e48 (object 0x0000000785ebcde0, a java.util.concurrent.ConcurrentLinkedQueue),
  which is held by "pool-1-thread-16"
"pool-1-thread-16":
  waiting to lock monitor 0x00002aab9be07670 (object 0x0000000785ebcba0, a io.socket.IOConnection),
  which is held by "ConnectThread"
"ConnectThread":
  waiting to lock monitor 0x00002aab9be10e48 (object 0x0000000785ebcde0, a java.util.concurrent.ConcurrentLinkedQueue),
  which is held by "pool-1-thread-16"
# Java stack information for the threads listed above:

"Thread-5789":
        at io.socket.IOConnection.sendPlain(IOConnection.java:449)
        - waiting to lock <0x0000000785ebcde0> (a java.util.concurrent.ConcurrentLinkedQueue)
        at io.socket.IOConnection.transportMessage(IOConnection.java:645)
        at io.socket.WebsocketTransport.onMessage(WebsocketTransport.java:117)
        at de.roderick.weberknecht.WebSocketReceiver.run(WebSocketReceiver.java:57)
"pool-1-thread-16":
        at io.socket.IOConnection.getState(IOConnection.java:849)
        - waiting to lock <0x0000000785ebcba0> (a io.socket.IOConnection)
        at io.socket.IOConnection.sendPlain(IOConnection.java:450)
        - locked <0x0000000785ebcde0> (a java.util.concurrent.ConcurrentLinkedQueue)
        at io.socket.IOConnection.emit(IOConnection.java:826)
        at io.socket.SocketIO.emit(SocketIO.java:236)  
        at benchmark.Benchmarker.RegisterInner(Benchmarker.java:215)
        at benchmark.Benchmarker.access$100(Benchmarker.java:48)
        at benchmark.Benchmarker$3.run(Benchmarker.java:204)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:662)
"ConnectThread": 
        at io.socket.IOConnection.transportConnected(IOConnection.java:518)
        - waiting to lock <0x0000000785ebcde0> (a java.util.concurrent.ConcurrentLinkedQueue)
        at io.socket.WebsocketTransport.onOpen(WebsocketTransport.java:123)
        at de.roderick.weberknecht.WebSocketConnection.connect(WebSocketConnection.java:139)
        at io.socket.WebsocketTransport.connect(WebsocketTransport.java:129)
        at io.socket.IOConnection.connectTransport(IOConnection.java:333)
        - locked <0x0000000785ebcba0> (a io.socket.IOConnection)
        at io.socket.IOConnection.access$200(IOConnection.java:38)
        at io.socket.IOConnection$ConnectThread.run(IOConnection.java:200)

Found 1 deadlock.

**Comment by Gottox** [comment]
Thanks for your bug report. Unfortunately I'm currently unavailable. I'll fix this at the end of next week.

**Comment by EugenDueck** [comment]
No hurry, my quick fix seems to work fine for me :)

**Comment by Gottox** [comment]
I removed the outBuffer lock and replaced them by this. This should fix this issue.

**Comment by EugenDueck** [comment]
Thanks. Will check it out, once I'm back benchmarking...
