### ISSUE TITLE
java.lang.IllegalStateException: Timer was canceled

### ISSUE THREAD

**Issue by ghost** [Gottox/socket.io-java-client#33]
Could not figure out how this happened. Sorry.  This is the error log.

java.lang.IllegalStateException: Timer was canceled
at java.util.Timer.scheduleImpl(Timer.java:561)
at java.util.Timer.schedule(Timer.java:459)
at io.socket.IOConnection.reconnect(Unknown Source)
at io.socket.IOConnection.transportDisconnected(Unknown Source)
at io.socket.WebsocketTransport.onClose(Unknown Source)
at org.java_websocket.client.WebSocketClient.onWebsocketClose(Unknown Source)
at org.java_websocket.WebSocketImpl.closeConnection(Unknown Source)
at org.java_websocket.WebSocketImpl.closeConnection(Unknown Source)
at org.java_websocket.WebSocketImpl.close(Unknown Source)
at org.java_websocket.WebSocketImpl.close(Unknown Source)
at org.java_websocket.client.WebSocketClient.interruptableRun(Unknown Source)
at org.java_websocket.client.WebSocketClient.run(Unknown Source)
at java.lang.Thread.run(Thread.java:856)

**Comment by pzmudzinski** [comment]
Any news on that?

**Comment by sooraj-e** [comment]
i had similar issue while using xhr. try this fix #44 worked for me.
