### ISSUE TITLE
Error on server restart

### ISSUE THREAD

**Issue by erelsgl** [Gottox/socket.io-java-client#41]
I started a socket.io server, then connected to it using a socket.io client, then I had to shut-down the server and start it again. The client showed the following cryptic exception:

io.socket.SocketIOException: 1+0
    at io.socket.IOConnection.transportMessage(IOConnection.java:737)
    at io.socket.WebsocketTransport.onMessage(WebsocketTransport.java:82)
    at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:361)
    at org.java_websocket.WebSocketImpl.deliverMessage(WebSocketImpl.java:565)
    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:331)
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:152)
    at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:247)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:193)
    at java.lang.Thread.run(Thread.java:722)
Exception in thread "Thread-16" java.lang.IllegalStateException: Timer already cancelled.
    at java.util.Timer.sched(Timer.java:397)
    at java.util.Timer.schedule(Timer.java:193)
    at io.socket.IOConnection.reconnect(IOConnection.java:766)
    at io.socket.IOConnection.transportDisconnected(IOConnection.java:559)
    at io.socket.WebsocketTransport.onClose(WebsocketTransport.java:76)

**Comment by se77en** [comment]
I have this error too.

**Comment by fatshotty** [comment]
could it be related to https://github.com/Gottox/socket.io-java-client/issues/44 ?
