### ISSUE TITLE
io.socket.SocketIOException: Error while handshaking

### ISSUE THREAD

**Issue by manthra** [Gottox/socket.io-java-client#45]
I just followed the instructions but I'm getting
following exception:

io.socket.SocketIOException: Error while handshaking
    at io.socket.IOConnection.handshake(IOConnection.java:322)
    at io.socket.IOConnection.access$600(IOConnection.java:39)
    at io.socket.IOConnection$ConnectThread.run(IOConnection.java:199)
Caused by: java.lang.NumberFormatException: For input string: ""
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
    at java.lang.Long.parseLong(Long.java:431)
    at java.lang.Long.parseLong(Long.java:468)
    at io.socket.IOConnection.handshake(IOConnection.java:318)
    ... 2 more
26 Mar, 2013 7:04:21 PM io.socket.IOConnection cleanup
INFO: Cleanup

**Comment by salomander86** [comment]
I think, I found the answer!!! The problem in handshake procces with server. When you make your first request, the server have to answer you with something like this: 
handshake (22)
- server_hello (2) 
- certificate (11) 
- server_key_exchange (12)
- certificate_request (13) 
- server_hello_done (14)

Thats mean that you have to identifiy your selve to server and server to you. 

For more info should read SSL handshake!

**Comment by ghost** [comment]
Could you give a little more info on how exactly you solved this, as I'm experiencing the same problem.

**Comment by yunqing** [comment]
I encountered the same problem. It took me a lot of time until I found the solution.The solution is just to use a previous version of socket.io at server end. I replaced 1.1.0 with 0.9.16 and everything goes fine. I found the solution here: http://stackoverflow.com/questions/24081179/gottox-socket-io-java-client-error-while-handshaking-caused-by-java-io-filenot
