### ISSUE TITLE
Can't disconnect xhr socket

### ISSUE THREAD

**Issue by sooraj-e** [Gottox/socket.io-java-client#47]
I'm trying to disconnect the socket when the user logs out. throws following error.
java.lang.IllegalStateException: Timer was canceled
  at java.util.Timer.scheduleImpl(Timer.java:561)
  at java.util.Timer.schedule(Timer.java:459)
  at io.socket.IOConnection.reconnect(IOConnection.java:766)
  at io.socket.IOConnection.transportDisconnected(IOConnection.java:559)
  at io.socket.XhrTransport$PollThread.run(XhrTransport.java:131)

socket connection is in xhr mode. trying to disconnect as socket.disconnect();

**Comment by sooraj-e** [comment]
this fix #44 works
