### ISSUE TITLE
server reconnection issue

### ISSUE THREAD

**Issue by mkuklis** [Gottox/socket.io-java-client#49]
Hi guys, I ran into an issue with the server reconnection. When the server goes down and then comes up again I get this exception on the client:

``` java
I/io.socket(  333): < 7:::1+0
I/System.out(  333): an Error occured
W/System.err(  333): io.socket.SocketIOException: 1+0
W/System.err(  333):    at io.socket.IOConnection.transportMessage(IOConnection.java:736)
W/System.err(  333):    at io.socket.WebsocketTransport.onMessage(WebsocketTransport.java:82)
W/System.err(  333):    at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:361)
W/System.err(  333):    at org.java_websocket.WebSocketImpl.deliverMessage(WebSocketImpl.java:565)
W/System.err(  333):    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:331)
W/System.err(  333):    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:152)
W/System.err(  333):    at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:247)
W/System.err(  333):    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:193)
W/System.err(  333):    at java.lang.Thread.run(Thread.java:1019)
I/io.socket(  333): Cleanup

```

**Comment by mkuklis** [comment]
I think this is probably the same issue as #4

**Comment by fatshotty** [comment]
hi,
that should be right. you should catch the exception and try to reconnect you client as per #4

**Comment by mkuklis** [comment]
@fatshotty thank you! That's indeed a case.
